# Generated by Django 4.2.1 on 2023-05-21 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(max_length=8)),
                ('fecha_pedido', models.DateTimeField(default=datetime.datetime.now)),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
    ]
