# Generated by Django 4.2.1 on 2023-05-21 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0002_alter_libro_autor_alter_libro_editorial_and_more'),
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='libro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='libro.libro'),
            preserve_default=False,
        ),
    ]
