# Generated by Django 4.2.1 on 2023-05-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0003_pedido_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
