# Generated by Django 4.2.1 on 2023-05-21 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0003_alter_libro_autor_alter_libro_editorial_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='estado',
            new_name='activo',
        ),
    ]
