# Generated by Django 4.2.1 on 2023-05-21 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='estado',
            new_name='activo',
        ),
    ]
