# Generated by Django 4.2.1 on 2023-05-21 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_rename_estado_cliente_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='mail',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
